# Generated by Django 2.1.3 on 2019-10-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='笔记名')),
                ('file', models.FileField(upload_to='notefile', verbose_name='笔记的markdown文件')),
                ('time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '笔记',
                'db_table': 'Note',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组名称')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='组成员个数')),
            ],
            options={
                'verbose_name_plural': '笔记的组',
                'db_table': 'NoteGroup',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoteRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('note_recode_category', models.PositiveSmallIntegerField(choices=[(0, '创建'), (1, '修改')], default=0, verbose_name='操作类别')),
                ('note', models.ManyToManyField(related_name='note', to='EO.Note', verbose_name='笔记')),
            ],
            options={
                'verbose_name_plural': '笔记修改记录',
                'db_table': 'NoteRecode',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12, verbose_name='用户id')),
                ('user_password', models.CharField(max_length=20, verbose_name='密码')),
                ('user_name', models.CharField(default='保密', max_length=12, verbose_name='姓名')),
                ('user_create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='noterecode',
            name='user',
            field=models.ManyToManyField(related_name='user', to='EO.User', verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='note',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoteGroup', to='EO.NoteGroup', verbose_name='笔记的组'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoteUser', to='EO.User', verbose_name='笔记创建人'),
        ),
    ]
