# Generated by Django 2.1.3 on 2019-10-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='笔记的markdown文件'),
        ),
    ]
