# Generated by Django 2.1.3 on 2019-10-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noterecode',
            name='note',
        ),
        migrations.AddField(
            model_name='noterecode',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='EO.Note', verbose_name='笔记'),
        ),
        migrations.RemoveField(
            model_name='noterecode',
            name='user',
        ),
        migrations.AddField(
            model_name='noterecode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='EO.User', verbose_name='修改人'),
        ),
    ]
