# Generated by Django 2.1.3 on 2019-10-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0002_auto_20191006_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='../cornerstoneFiles/', verbose_name='笔记的markdown文件'),
        ),
    ]
