# Generated by Django 2.1.3 on 2020-05-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0003_auto_20191006_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('contain', models.CharField(max_length=100, verbose_name='内容')),
                ('verify', models.BooleanField(default=False, verbose_name='是否通过')),
            ],
            options={
                'verbose_name_plural': '520弹幕',
                'db_table': 'BulletChat',
                'ordering': ['id'],
            },
        ),
    ]
