# Generated by Django 2.1.3 on 2019-10-06 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0003_auto_20191006_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '笔记修改记录',
                'db_table': 'NoteRecode',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noterecode',
            name='note',
            field=models.ManyToManyField(related_name='note', to='EO.Note', verbose_name='笔记'),
        ),
        migrations.AddField(
            model_name='noterecode',
            name='user',
            field=models.ManyToManyField(related_name='user', to='EO.User', verbose_name='修改人'),
        ),
    ]
