# Generated by Django 2.1.3 on 2019-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EO', '0004_auto_20191006_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='noterecode',
            name='note_recode_category',
            field=models.PositiveSmallIntegerField(choices=[(0, '创建'), (1, '修改')], default=0, verbose_name='操作类别'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='noterecode',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
